# Generated by Django 5.1.1 on 2024-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_moodentry_feelings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='feelings',
            field=models.TextField(),
        ),
    ]
