# Generated by Django 5.1.3 on 2024-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_moodentry_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
